/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neptune_api_MIH */

#ifndef _Included_com_neptune_api_MIH
#define _Included_com_neptune_api_MIH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neptune_api_MIH
 * Method:    init
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_neptune_api_MIH_init
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_neptune_api_MIH
 * Method:    appendCodes
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_neptune_api_MIH_appendCodes
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_neptune_api_MIH
 * Method:    getCandidates
 * Signature: ([BZI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_neptune_api_MIH_getCandidates
  (JNIEnv *, jclass, jbyteArray, jboolean, jint);

/*
 * Class:     com_neptune_api_MIH
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_neptune_api_MIH_destory
  (JNIEnv *, jclass);

/*
 * Class:     com_neptune_api_MIH
 * Method:    rotateNewDayCodes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_neptune_api_MIH_rotateNewDayCodes
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
